version: '3.3'
services:
   db:
      image: mysql:8.0
      cap_add:
         - SYS_NICE
      restart: always
      hostname: mysql
      container_name: mysql
      environment:
         MYSQL_DATABASE: 'net'
         MYSQL_USER: 'net'
         MYSQL_ROOT_PASSWORD: 'net'
         MYDATA: /var/lib/mysql/
      ports:
         - '3306:3306'
      volumes:
         - db:/var/lib/mysql
volumes:
   db:
     driver: local 
