version: "3.3"
services: 
  db:
     image: postgres:12
     restart: always
     hostname: postgres12    
     container_name: db_post
     environment:
          POSTGRES_DB: "test"
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: "test"
          PGDATA: /var/lib/postgresql/data/pgdata          
     volumes:
          - data:/var/lib/postgresql/data:rw
          - bkp:/var/lib/postgresql/
     ports:
          - 5432:5432
volumes:
       data:
       bkp:
